name: Feature request or enhancement
description: Request for a new component or enhancement of a component
title: 'Lyne: [Feature request]: '
labels: ['type: enhancement 💡']
body:
  - type: dropdown
    id: new-or-enhancement
    attributes:
      label: Request type
      options:
        - 'Request for a new component'
        - 'Request for enhancement of a component'
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Functionality
      description: For what purpose is the component used? What features does it need to have? Which component should be enhanced?
    validations:
      required: true
  - type: dropdown
    id: proposal
    attributes:
      label: Is there a design proposal?
      description: Design proposals are optional, our UX experts will work with you to develop a proposal
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to design proposal file (optional)
      description: e.g. Figma-Link or Sketch-Link
    validations:
      required: false
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the issue tracker for an issue that matches the one I want to file, without success.
          required: true