name: Question
description: Usage question or discussion about Components or Design Tokens
title: "[Question]: "
labels: ['type: question']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Hi there! 👋🏻 We hope everything is fine using our projects from the Lyne Design System. It looks like you might have a question about our work, so we wanted to share some resources that you could use if you have not tried them yet 🙂.
        You can find the Lyne Components documentation [here](https://github.com/lyne-design-system/lyne-components/docs). Also have first a look at our [issues](https://github.com/lyne-design-system/lyne-components/issues) if your question/issue has been asked/raised before or even might have been solved.
        If these resources do not work out, help us out by filling out a couple of details below!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the issue tracker for an issue that matches the one I want to file, without success.
          required: true
  - type: markdown
    attributes:
      value: |
        ## Your question
  - type: dropdown
    id: component-or-design-token
    attributes:
      label: It affects the following packages
      options:
        - 'Design Tokens'
        - 'Components'
        - 'Design Tokens & Components'
        - 'Other'
    validations:
      required: true
  - type: input
    id: question
    attributes:
      label: Your Question
    validations:
      required: true 
  - type: textarea
    id: relevant-information
    attributes:
      label: Give us a summary about your question
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Provide as much useful information as you can, e.g. Links to Figma or other references
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true



      